// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClosedDay = "closed_days"

// ClosedDay mapped from table <closed_days>
type ClosedDay struct {
	Date    time.Time `gorm:"column:date;primaryKey" json:"date"`
	Summary string    `gorm:"column:summary;not null" json:"summary"`
}

// TableName ClosedDay's table name
func (*ClosedDay) TableName() string {
	return TableNameClosedDay
}
