// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"net.bright-room.dev/calender-api/internal/infrastructure/datasource/db/entity"
)

func newClosedDay(db *gorm.DB, opts ...gen.DOOption) closedDay {
	_closedDay := closedDay{}

	_closedDay.closedDayDo.UseDB(db, opts...)
	_closedDay.closedDayDo.UseModel(&entity.ClosedDay{})

	tableName := _closedDay.closedDayDo.TableName()
	_closedDay.ALL = field.NewAsterisk(tableName)
	_closedDay.Date = field.NewTime(tableName, "date")
	_closedDay.Summary = field.NewString(tableName, "summary")

	_closedDay.fillFieldMap()

	return _closedDay
}

type closedDay struct {
	closedDayDo closedDayDo

	ALL     field.Asterisk
	Date    field.Time
	Summary field.String

	fieldMap map[string]field.Expr
}

func (c closedDay) Table(newTableName string) *closedDay {
	c.closedDayDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c closedDay) As(alias string) *closedDay {
	c.closedDayDo.DO = *(c.closedDayDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *closedDay) updateTableName(table string) *closedDay {
	c.ALL = field.NewAsterisk(table)
	c.Date = field.NewTime(table, "date")
	c.Summary = field.NewString(table, "summary")

	c.fillFieldMap()

	return c
}

func (c *closedDay) WithContext(ctx context.Context) *closedDayDo {
	return c.closedDayDo.WithContext(ctx)
}

func (c closedDay) TableName() string { return c.closedDayDo.TableName() }

func (c closedDay) Alias() string { return c.closedDayDo.Alias() }

func (c closedDay) Columns(cols ...field.Expr) gen.Columns { return c.closedDayDo.Columns(cols...) }

func (c *closedDay) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *closedDay) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["date"] = c.Date
	c.fieldMap["summary"] = c.Summary
}

func (c closedDay) clone(db *gorm.DB) closedDay {
	c.closedDayDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c closedDay) replaceDB(db *gorm.DB) closedDay {
	c.closedDayDo.ReplaceDB(db)
	return c
}

type closedDayDo struct{ gen.DO }

func (c closedDayDo) Debug() *closedDayDo {
	return c.withDO(c.DO.Debug())
}

func (c closedDayDo) WithContext(ctx context.Context) *closedDayDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c closedDayDo) ReadDB() *closedDayDo {
	return c.Clauses(dbresolver.Read)
}

func (c closedDayDo) WriteDB() *closedDayDo {
	return c.Clauses(dbresolver.Write)
}

func (c closedDayDo) Session(config *gorm.Session) *closedDayDo {
	return c.withDO(c.DO.Session(config))
}

func (c closedDayDo) Clauses(conds ...clause.Expression) *closedDayDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c closedDayDo) Returning(value interface{}, columns ...string) *closedDayDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c closedDayDo) Not(conds ...gen.Condition) *closedDayDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c closedDayDo) Or(conds ...gen.Condition) *closedDayDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c closedDayDo) Select(conds ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c closedDayDo) Where(conds ...gen.Condition) *closedDayDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c closedDayDo) Order(conds ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c closedDayDo) Distinct(cols ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c closedDayDo) Omit(cols ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c closedDayDo) Join(table schema.Tabler, on ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c closedDayDo) LeftJoin(table schema.Tabler, on ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c closedDayDo) RightJoin(table schema.Tabler, on ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c closedDayDo) Group(cols ...field.Expr) *closedDayDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c closedDayDo) Having(conds ...gen.Condition) *closedDayDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c closedDayDo) Limit(limit int) *closedDayDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c closedDayDo) Offset(offset int) *closedDayDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c closedDayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *closedDayDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c closedDayDo) Unscoped() *closedDayDo {
	return c.withDO(c.DO.Unscoped())
}

func (c closedDayDo) Create(values ...*entity.ClosedDay) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c closedDayDo) CreateInBatches(values []*entity.ClosedDay, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c closedDayDo) Save(values ...*entity.ClosedDay) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c closedDayDo) First() (*entity.ClosedDay, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ClosedDay), nil
	}
}

func (c closedDayDo) Take() (*entity.ClosedDay, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ClosedDay), nil
	}
}

func (c closedDayDo) Last() (*entity.ClosedDay, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ClosedDay), nil
	}
}

func (c closedDayDo) Find() ([]*entity.ClosedDay, error) {
	result, err := c.DO.Find()
	return result.([]*entity.ClosedDay), err
}

func (c closedDayDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ClosedDay, err error) {
	buf := make([]*entity.ClosedDay, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c closedDayDo) FindInBatches(result *[]*entity.ClosedDay, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c closedDayDo) Attrs(attrs ...field.AssignExpr) *closedDayDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c closedDayDo) Assign(attrs ...field.AssignExpr) *closedDayDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c closedDayDo) Joins(fields ...field.RelationField) *closedDayDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c closedDayDo) Preload(fields ...field.RelationField) *closedDayDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c closedDayDo) FirstOrInit() (*entity.ClosedDay, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ClosedDay), nil
	}
}

func (c closedDayDo) FirstOrCreate() (*entity.ClosedDay, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ClosedDay), nil
	}
}

func (c closedDayDo) FindByPage(offset int, limit int) (result []*entity.ClosedDay, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c closedDayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c closedDayDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c closedDayDo) Delete(models ...*entity.ClosedDay) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *closedDayDo) withDO(do gen.Dao) *closedDayDo {
	c.DO = *do.(*gen.DO)
	return c
}
