// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNationalHoliday = "national_holiday"

// NationalHoliday mapped from table <national_holiday>
type NationalHoliday struct {
	Date    time.Time `gorm:"column:date;primaryKey" json:"date"`
	Summary string    `gorm:"column:summary;not null" json:"summary"`
}

// TableName NationalHoliday's table name
func (*NationalHoliday) TableName() string {
	return TableNameNationalHoliday
}
